version: '2'
services:
  postgrest:
    image: postgrest/postgrest:v6.0.2
    environment:
      - PGRST_DB_URI=postgres://postgres@db:5432/ferflix
      - PGRST_DB_ANON_ROLE=postgres
    ports:
      - "3000:3000"
    restart: always

  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=ferflix
    volumes:
      - ./migrations:/migrations
    ports:
      - "5432:5432"
    restart: always